spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - SaveSession
          routes:
            - id: api
              order: 1000
              uri: ${API_HOST:http://api.yas.local.com}
              predicates:
                - Path=/api/**
              filters:
                - DedupeResponseHeader=Origin Access-Control-Request-Method Access-Control-Request-Headers
                - TokenRelay=
                - StripPrefix=1
            - id: nextjs
              order: 2000
              uri: ${UI_HOST:http://storefront-nextjs:3000}
              predicates:
                - Path=/**
